### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by Panquesito7** [FaceDeer/mapgen_helper#1]
Currently, there's a empty `depends.txt`. This should be deleted, plus, it is deprecated.
`description.txt` should be also deleted.

Also, `mod.conf` has `optional_depends` and `depends`. This is not needed as there are no (soft) dependencies in this mod.

**Comment by sofar** [comment]
Send patch. ""you can do it!""

**Comment by Panquesito7** [comment]
> Send patch. ""you can do it!""

Heheh, I'll create it right now. 🙂
